#pragma once
#define IMAGE_SIZE 125
#define NORMAL 0
#define PINK 255
#define Y 8
#define X 8
#define PIECE_MAX 16
#define NONE -1
#define WHITE_KING 11
#define BLACK_KING 12
struct ImageInfo
{
	int m_iImageIndex;
	RECT m_ImageRect;
};
enum IMAGE
{
	IMAGE_START,
	IMAGE_BLOCK_IVORY = 0,
	IMAGE_BLOCK_BROWN,
	IMAGE_BLOCK_PINK,
	IMAGE_BLACK_PAWN,
	IMAGE_BLACK_KNIGHT,
	IMAGE_BLACK_BISHOP,
	IMAGE_BLACK_ROCK,
	IMAGE_BLACK_QUEEN,
	IMAGE_BLACK_KING,
	IMAGE_WHITE_PAWN,
	IMAGE_WHITE_KNIGHT,
	IMAGE_WHITE_BISHOP,
	IMAGE_WHITE_ROCK,
	IMAGE_WHITE_QUEEN,
	IMAGE_WHITE_KING,
	IMAGE_MAX
};
enum TYPE
{
	TYPE_WHITE,
	TYPE_BLACK,
	TYPE_MAX
};