#pragma once
#pragma comment(lib, "msimg32.lib")
#include<windows.h>

#define IMAGE_SIZE 50
#define ROOM 13
#define WIN_X IMAGE_SIZE * 16
#define WIN_Y IMAGE_SIZE * 15
#define MAP_MAX 5

enum IMAGE
{
	IMAGE_START,
	IMAGE_LOBBY = 0,
	IMAGE_BACK,
	IMAGE_BLOCK1,
	IMAGE_BLOCK1_UP,
	IMAGE_BLOCK1_LEFT,
	IMAGE_BLOCK1_DOWN,
	IMAGE_BLOCK1_RIGHT,
	IMAGE_BLOCK2,
	IMAGE_BLOCK2_UP,
	IMAGE_BLOCK2_RIGHT,
	IMAGE_BLOCK2_DOWN,
	IMAGE_BLOCK2_RIGHT2,
	IMAGE_BLOCK_STEEL,
	IMAGE_BLOCK_WOOD,
	IMAGE_BLOCK_WATER,
	IMAGE_ITEM1,
	IMAGE_ITEM2,
	IMAGE_ENEMY_DOWN1,
	IMAGE_ENEMY_DOWN2,
	IMAGE_ENEMY_LEFT1,
	IMAGE_ENEMY_LEFT2,
	IMAGE_ENEMY_RIGHT1,
	IMAGE_ENEMY_RIGHT2,
	IMAGE_ENEMY_UP1,
	IMAGE_ENEMY_UP2,
	IMAGE_PLAYER_DOWN1,
	IMAGE_PLAYER_DOWN2,
	IMAGE_PLAYER_LEFT1,
	IMAGE_PLAYER_LEFT2,
	IMAGE_PLAYER_RIGHT1,
	IMAGE_PLAYER_RIGHT2,
	IMAGE_PLAYER_UP1,
	IMAGE_PLAYER_UP2,
	IMAGE_PLAYER_DOWN_ITEM,
	IMAGE_PLAYER_LEFT_ITEM,
	IMAGE_PLAYER_UP_ITEM,
	IMAGE_PLAYER_RIGHT_ITEM,
	IMAGE_ENEMY_DIE1,
	IMAGE_ENEMY_DIE2,
	IMAGE_ENEMY_DIE3,
	IMAGE_PLAYER_DIE1,
	IMAGE_PLAYER_DIE2,
	IMAGE_EMEY_ICON,
	IMAGE_PLAYER_ICON,
	IMAGE_SHIELD1,
	IMAGE_SHIELD2,
	IMAGE_BULLET,
	IMAGE_STAGE,
	IMAGE_MAX
};

enum BLOCK_STATE
{
	BLOCK_STATE_EMPTY,
	BLOCK_STATE_NOTHING,
	BLOCK_STATE_BREAK,
	BLOCK_STATE_FIX
};

struct Room
{
	int m_iIndex;
	int m_iState;
	POINT m_Point;
	SIZE m_Size;
	RECT m_Rect;
};