#pragma once
#pragma comment(lib, "msimg32.lib")
#include<windows.h>
#include<time.h>
#define GALLERY_MAX 11
#define RING_MAX 3
#define WIN_SIZE 1000
#define LEFT 10
#define RIGHT -10
#define JUMP 0
enum IMAGE
{
	IMAGE_START,
	IMAGE_LANE = 0,
	IMAGE_DECO,
	IMAGE_PEOPLE1,
	IMAGE_PEOPLE2,
	IMAGE_MONEY,
	IMAGE_DIE,
	IMAGE_WIN1,
	IMAGE_WIN2,
	IMAGE_GOAL,
	IMAGE_ENEMY1,
	IMAGE_ENEMY1_RIGHT,
	IMAGE_ENEMY2,
	IMAGE_ENEMY2_RIGHT,
	IMAGE_ENEMY3,
	IMAGE_ENEMY3_RIGHT,
	IMAGE_FIRE1,
	IMAGE_FIRE2,
	IMAGE_MITER,
	IMAGE_CHAR1,
	IMAGE_CHAR2,
	IMAGE_CHAR3,
	IMAGE_MAX
};

struct MyIMG
{
	int m_iIndex;
	POINT m_Point;
	SIZE m_Size;
	RECT m_Rect1;
	RECT m_Rect2;
};