#pragma once
#include<windows.h>
#include<time.h>
#define NORMAL 0
#define BACK 1
#define WIN_X 1024
#define WIN_Y 768
#define LEFT 1
#define RIGHT 2
#define JUMP 50
#define GRAVITY -10
#define RING_MAX 3
#define FIRE_MAX 10
#define MITER_MAX 10
enum IMAGE
{
	IMAGE_START,
	IMAGE_BACK = 0,
	IMAGE_BACK_DECO,
	IMAGE_BACK_NORMAL,
	IMAGE_BACK_NORMAL2,
	IMAGE_CASH,
	IMAGE_DIE,
	IMAGE_END,
	IMAGE_ENEMY,
	IMAGE_ENEMY_BACK,
	IMAGE_ENEMY_FRONT,
	IMAGE_ENEMY1,
	IMAGE_ENEMY1_BACK,
	IMAGE_ENEMY1_FRONT,
	IMAGE_ENEMY2,
	IMAGE_ENEMY2_BACK,
	IMAGE_ENEMY2_FRONT,
	IMAGE_FIRE1,
	IMAGE_FIRE2,
	IMAGE_GAME_ICON,
	IMAGE_MITER,
	IMAGE_PLAYER,
	IMAGE_PLAYER1,
	IMAGE_PLAYER2,
	IMAGE_STAR,
	IMAGE_STAR1,
	IMAGE_STAR2,
	IMAGE_PLAYER_WIN,
	IMAGE_PLAYER_WIN2,
	IMAGE_MAX
};

struct MyIMG
{
	int m_iIndex;
	POINT m_iPoint;
	SIZE m_iSize;
};
