#pragma once
#pragma comment(lib, "msimg32.lib")
#include<windows.h>
#include<conio.h>
#include<time.h>
#include"resource.h"
#include<string>
#define IMG_SIZE 50
#define WIN_X 800
#define WIN_Y 750
#define ROOM 13
#define EMPTY -1
#define MAP_MAX 5

using namespace std;
enum IMAGE
{
	IMAGE_START,
	IMAGE_BLOCK1 = 0,
	IMAGE_BLOCK1_UP,
	IMAGE_BLOCK1_LEFT,
	IMAGE_BLOCK1_DOWN,
	IMAGE_BLOCK1_RIGHT,
	IMAGE_BLOCK2,
	IMAGE_BLOCK2_UP,
	IMAGE_BLOCK2_LEFT,
	IMAGE_BLOCK2_DOWN,
	IMAGE_BLOCK2_RIGHT,
	IMAGE_ITEM1,
	IMAGE_ITEM2,
	IMAGE_ENEMY1_DOWN1,
	IMAGE_ENEMY1_DOWN2,
	IMAGE_ENEMY1_LEFT1,
	IMAGE_ENEMY1_LEFT2,
	IMAGE_ENEMY1_RIGHT1,
	IMAGE_ENEMY1_RIGHT2,
	IMAGE_ENEMY1_UP1,
	IMAGE_ENEMY1_UP2,
	IMAGE_ENEMY2_DOWN,
	IMAGE_ENEMY2_LEFT,
	IMAGE_ENEMY2_RIGHT,
	IMAGE_ENEMY2_UP,
	IMAGE_PLAYER_DOWN1,
	IMAGE_PLAYER_DOWN2,
	IMAGE_PLAYER_LEFT1,
	IMAGE_PLAYER_LEFT2,
	IMAGE_PLAYER_RIGHT1,
	IMAGE_PLAYER_RIGHT2,
	IMAGE_PLAYER_UP1,
	IMAGE_PLAYER_UP2,
	IMAGE_ENEMY_BREAK1,
	IMAGE_ENEMY_BREAK2,
	IMAGE_ENEMY_BREAK3,
	IMAGE_PLAYER_BREAK1,
	IMAGE_PLAYER_BREAK2,
	IMAGE_SHIELD1,
	IMAGE_SHIELD2,
	IMAGE_ENEMY_ICON,
	IMAGE_PLAYER_ICON,
	IMAGE_BULLET,
	IMAGE_BACK,
	IMAGE_EMPTY,
	IMAGE_MAX
};

enum BUTTON
{
	BUTTON_START,
	BUTTON_EMPTY = 0,
	BUTTON_BREAK_WALL,
	BUTTON_FIX_WALL,
	BUTTON_MAX
};

enum STATE
{
	STATE_EMPTY,
	STATE_FULL,
	STATE_FIX
};

struct Room
{
	int m_iIndex;
	int m_iState;
	POINT m_Point;
	SIZE m_Size;
	RECT m_Rect;
};